### ISSUE TITLE
Config may be out of date for angular cli/webpack - No compilers found, is not instrumented by core, No preprocessors configured for

### ISSUE THREAD

**Issue by NateMay** [wallabyjs/ngCliWebpackSample#18]
I've followed the README in this repo, but I'm having trouble that doesn't seem to parallel similar issue found on github.

My `wallaby.js` is cut and paste from this repo ([link](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js)), and I will include my `tsconfig.json`s below.

When I run wallaby start the log follows this pattern for `.ts`, `.scss`, and `html` (I'll post for only 1 file)

```
wallaby:project File added: src/app/search/search.comp.spec.ts
...
wallaby:project File src/app/search/search.comp.spec.ts changes are patches only: false
...
wallaby:project Preparing to process src/app/search/search.comp.spec.ts
...
wallaby:processor No compilers found for src/app/search/search.comp.spec.ts
wallaby:project File src/app/search/search.comp.spec.ts is not instrumented by core
wallaby:project No preprocessors configured for src/app/search/search.comp.spec.ts
wallaby:project Writing to disk and caching processed file src/app/search/search.comp.spec.ts
...
wallaby:project File src/app/search/search.comp.spec.ts changes saved, store ts: 1497758020000, change ts: 1497901...
```

and the end of the log is as follows

```
[Info]​​​​​ Mon, 19 Jun 2017 20:24:22 GMT wallaby:project Stopping process pool
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:22 GMT wallaby:project Running postprocessor
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:22 GMT wallaby:postprocessor New TypeScript language service is required
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:22 GMT wallaby:postprocessor TypeScript compiler options module (before tsconfig.json): 1
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:23 GMT wallaby:postprocessor TypeScript compiler options module (after tsconfig.json): 1
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:30 GMT wallaby:postprocessor New compiler created
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:30 GMT wallaby:project Error
​​​​​[Info]​​​​​   at WebpackPostprocessor.webpack [as _webpack] (/Users/<project_path>/node_modules/webpack/lib/webpack.js:19:9)
​​​​​[Info]​​​​​   at WebpackPostprocessor._createCompiler (/Users/nathanielmay/Code/v8/node_modules/wallaby-webpack/index.js:270:41)
​​​​​[Info]​​​​​   at wallaby (/Users/nathanielmay/Code/v8/node_modules/wallaby-webpack/index.js:112:31)
​​​​​[Info]​​​​​   at /Users/nathanielmay/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.51/wallaby/server.js:16:23254
​​​​​[Info]​​​​​   at _combinedTickCallback (internal/process/next_tick.js:67:7)
​​​​​[Info]​​​​​   at process._tickCallback (internal/process/next_tick.js:98:9)
​​​​​[Info]​​​​​ From previous event:
​​​​​[Info]​​​​​   at /Users/nathanielmay/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.51/wallaby/server.js:17:6129
​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/nathanielmay/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.51/wallaby/server.js:17:5550)
​​​​​[Info]​​​​​   at ontimeout (timers.js:365:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:237:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:207:5)
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:30 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:30 GMT wallaby:project Test run data re-queued

```

tsconfig.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noImplicitAny": true,
    "noEmitOnError": true,
    "target": "es5",
    "lib": [
      "es2016",
      "dom"
    ]
  },
  "exclude": [
    "src/wallabyTest.ts"
  ]
}
```

src/tsconfig.spec.json

```
{
  "compilerOptions": {
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2016",
      "dom"
    ],
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es5",
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by ArtemGovorov** [comment]
The config is up-to-date, and the `No compilers found, is not instrumented by core, No preprocessors configured for` messages are expected (these are just debugging messages from wallaby execution pipeline).

This error however is different (and not expected):

```
​​​​​[Info]​​​​​ Mon, 19 Jun 2017 20:24:30 GMT wallaby:project Error
​​​​​[Info]​​​​​   at WebpackPostprocessor.webpack [as _webpack] (/Users/<project_path>/node_modules/webpack/lib/webpack.js:19:9)
```
According to the stack, there's something wrong with webpack validating the config that wallaby is passing. Two things that are strange: if you're using the wallaby config you've linked as is without any changes, then it should work; and the error from webpack should be a bit more descriptive (it normally contains a long message starting with: `WebpackOptionsValidationError: Invalid configuration object....` ).

Let's try something:
- first, check the output of the Wallaby.js Tests output channel in VS Code (not just Wallaby Console), does it have any useful info there?
- next, try cloning the sample project https://github.com/wallabyjs/ngCliWebpackSample, running `npm install` and running wallaby to see if it's working for you.
- if the sample works (the sample is just the result of running the latest `ng new` plus wallaby config and dependencies), then please share your project sample reproducing the issue. It shouldn't be hard to extract, because in your case the build fails even before it get to your source files/tests. So you may just leave one empty test file in the repro project, the issue should still be reproducible.

**Comment by NateMay** [comment]
My Test Output isn't helpful:

```
Uncaught TypeError: Cannot read property 'loadTests' of undefined​​
​​at http://localhost:54551/wallaby_sandbox0.html:10​​
```
I installed the sample project and wallaby worked just fine.

I also created a sample project [https://github.com/NateMay/wallaby](https://github.com/NateMay/wallaby)

same issue, but I am getting a more verbose response:

```
[Info]​​​​​ Tue, 20 Jun 2017 01:27:10 GMT wallaby:postprocessor New compiler created
​​​​​[Info]​​​​​ Tue, 20 Jun 2017 01:27:10 GMT wallaby:project WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
​​​​​[Info]​​​​​  - configuration.entry should be one of these:
​​​​​[Info]​​​​​    object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
​​​​​[Info]​​​​​    The entry point(s) of the compilation.
​​​​​[Info]​​​​​    Details:
​​​​​[Info]​​​​​     * configuration.entry should NOT have less than 1 properties ({
​​​​​[Info]​​​​​         "keyword": "minProperties",
​​​​​[Info]​​​​​         "dataPath": ".entry",
​​​​​[Info]​​​​​         "schemaPath": "#/oneOf/0/minProperties",
​​​​​[Info]​​​​​         "params": {
​​​​​[Info]​​​​​           "limit": 1
​​​​​[Info]​​​​​         },
​​​​​[Info]​​​​​         "message": "should NOT have less than 1 properties",
​​​​​[Info]​​​​​         "schema": 1,
​​​​​[Info]​​​​​         "parentSchema": {
​​​​​[Info]​​​​​           "minProperties": 1,
​​​​​[Info]​​​​​           "additionalProperties": {
​​​​​[Info]​​​​​             "oneOf": [
​​​​​[Info]​​​​​               {
​​​​​[Info]​​​​​                 "description": "The string is resolved to a module which is loaded upon startup.",
​​​​​[Info]​​​​​                 "minLength": 1,
​​​​​[Info]​​​​​                 "type": "string"
​​​​​[Info]​​​​​               },
​​​​​[Info]​​​​​               {
​​​​​[Info]​​​​​                 "description": "All modules are loaded upon startup. The last one is exported.",
​​​​​[Info]​​​​​                 "$ref": "#/definitions/common.nonEmptyArrayOfUniqueStringValues"
​​​​​[Info]​​​​​               }
​​​​​[Info]​​​​​             ]
​​​​​[Info]​​​​​           },
​​​​​[Info]​​​​​           "description": "Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.",
​​​​​[Info]​​​​​           "type": "object"
​​​​​[Info]​​​​​         },
​​​​​[Info]​​​​​         "data": {}
​​​​​[Info]​​​​​       }).
​​​​​[Info]​​​​​       object { <key>: non-empty string | [non-empty string] }
​​​​​[Info]​​​​​       Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
​​​​​[Info]​​​​​     * configuration.entry should be a string.
​​​​​[Info]​​​​​     * configuration.entry should be an array:
​​​​​[Info]​​​​​       [non-empty string]
​​​​​[Info]​​​​​     * configuration.entry should be an instance of function
​​​​​[Info]​​​​​       function returning an entry object or a promise..
​​​​​[Info]​​​​​   at WebpackPostprocessor.webpack [as _webpack] (/Users/nathanielmay/Desktop/test/node_modules/webpack/lib/webpack.js:19:9)
​​​​​[Info]​​​​​   at WebpackPostprocessor._createCompiler (/Users/nathanielmay/Desktop/test/node_modules/wallaby-webpack/index.js:270:41)
​​​​​[Info]​​​​​   at wallaby (/Users/nathanielmay/Desktop/test/node_modules/wallaby-webpack/index.js:112:31)
​​​​​[Info]​​​​​   at /Users/nathanielmay/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.51/wallaby/server.js:16:23254
​​​​​[Info]​​​​​   at _combinedTickCallback (internal/process/next_tick.js:67:7)
​​​​​[Info]​​​​​   at process._tickCallback (internal/process/next_tick.js:98:9)
​​​​​[Info]​​​​​ From previous event:
​​​​​[Info]​​​​​   at /Users/nathanielmay/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.51/wallaby/server.js:17:6129
​​​​​[Info]​​​​​   at Timeout._onTimeout (/Users/nathanielmay/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.51/wallaby/server.js:17:5550)
​​​​​[Info]​​​​​   at ontimeout (timers.js:365:14)
​​​​​[Info]​​​​​   at tryOnTimeout (timers.js:237:5)
​​​​​[Info]​​​​​   at Timer.listOnTimeout (timers.js:207:5)
​​​​​[Info]​​​​​ Tue, 20 Jun 2017 01:27:10 GMT wallaby:project Test run finished
​​​​​[Info]​​​​​ Tue, 20 Jun 2017 01:27:10 GMT wallaby:project Test run data re-queued
```

**Comment by ArtemGovorov** [comment]
Thanks for sharing the project.

After a bit of digging, it turned out that TypeScript compiler didn't generate any JS files. The issue was caused by the `compilerOptions.noEmitOnError` setting that is set to `true` in your project's `tsconfig.json` (and not set in the `ng new` generated sample). 

I have sent you [the PR to make it work](https://github.com/NateMay/wallaby/pull/1).

We'll also change wallaby TS compiler to ignore the setting (wallaby should work regardless of any missing `.d.ts` files, or type issues, etc.) and will use the correct default value.

**Comment by NateMay** [comment]
First off, thank you so so much for your support.

Your fix solved the issue. I did have anther issue that I solved by extracting my mock data from my spec files. I'm not sure why, but exporting mock data from spec files created a `module not found issue`. if there is any documentation on that, I would appreciate a link.

Thanks again and feel free to close the issue.

**Comment by ArtemGovorov** [comment]
>  I did have anther issue that I solved by extracting my mock data from my spec files.

Yep, [test files](https://wallabyjs.com/docs/config/files.html#tests) in `wallaby-webpack` context are entry files that can not be imported from else where (because they are entry points), so helpers, mock data an other test supporting files are supposed to be listed in the `files` list. The limitation in your specific case is coming not as much from wallaby, but from `wallaby-webpack`/`webpack`.
